### ISSUE TITLE
collision

### ISSUE THREAD

**Issue by catafest** [wybiral/terrain#2]
I think you need this to fix step 5. 
http://gamedevelopment.tutsplus.com/tutorials/webgl-physics-and-collision-detection-using-babylonjs-and-oimojs--cms-24114

**Comment by wybiral** [comment]
What's wrong with [step 5](https://github.com/wybiral/terrain/releases/tag/0.5)?

Babylon.js seems neat, but the goal here is to create a simple 3d terrain demo using [three.js](http://threejs.org/docs/index.html#Manual/Introduction/Creating_a_scene).

**Comment by catafest** [comment]
it's about the physics engine companion named Oimo.js to solve collision. 
_note: yes , I saw you use three.js you need to fix material with normal texture , ambient occlusion_
